[binance_pipeline.destination.clickhouse.credentials]
host = "localhost"
database = "default"
username = "default"
password = ""

# IMPORTANT: specify both ports explicitly
native_port = 9000    # for native driver
http_port   = 8123    # for HTTP loader

# no TLS locally
secure = 0            # (0 = off, 1 = on)